### ISSUE TITLE
should on Exit exception be suppressed by ignoreErrors?

### ISSUE THREAD

**Issue by rommik** [Klathmon/gulp-run-command#1]
It seems that if 

````
proc.on('exit', (code) => {
    if (parseInt(code, 10) === 0) {
      resolve()
    } else {
      throw new Error(`Non-zero exit code of "${code}"`)
    }
  })
````
enters new Error, while ignoreErrors = true. The Exception is not caught or suppressed by the top try /catch. Has this always been the intended functionality or is it a bug?

**Comment by Klathmon** [comment]
You are right, that's a mistake on my part! I'll close this here and continue the conversation in #2
