### ISSUE TITLE
command is not run, no output

### ISSUE THREAD

**Issue by tommedema** [Klathmon/gulp-run-command#4]
Not sure what I'm doing wrong, but I am replacing a npm script. This was my package.json:

```
{
  ...
  "scripts": {
    "deploy-stage": "export AWS_PROFILE=${PROJECT}-${STAGE} && ../../node_modules/serverless/bin/serverless deploy --verbose --stage $STAGE --region eu-west-2 --aws-s3-accelerate",
  }
```

And this is the gulp version:

```
const gulp = require('gulp')
const gutil = require('gulp-util')
const run = require('gulp-run-command').default

gulp.task('deploy', () => {
  const PROJECT = 'sls'
  const STAGE = 'dev'
  const REGION = 'eu-west-2'
  
  run(`${__dirname}/../../node_modules/serverless/bin/serverless deploy
    --verbose --stage ${STAGE} --region ${REGION} --aws-s3-accelerate`, {
      env: {
        AWS_PROFILE: `${PROJECT}-${STAGE}`
      }
  })
  
  gutil.log('post-deploy')
})
```

But when I run `gulp deploy`, it gives:

```
Toms-MBP-2:api tommedema$ gulp deploy
[23:45:02] Using gulpfile ~/Drive/education/serverless/serverless-aws-crud-starter/services/api/gulpfile.js
[23:45:02] Starting 'deploy'...
[23:45:02] post-deploy
[23:45:02] Finished 'deploy' after 3.72 ms
```

Without any error messages whatsoever. I thought it could be since there is no use of `async/await`, promises, or callbacks (so gulp wouldn't know when `run` was finished); but then again you are not doing this in your example either.

This is with node v8.9.3 LTS

**Comment by Klathmon** [comment]
It's not obvious, but when used like that you need to re-invoke the function that run returns.

So you would need to modify your function to look like this:

```
const gulp = require('gulp')
const gutil = require('gulp-util')
const run = require('gulp-run-command').default

gulp.task('deploy', () => {
  const PROJECT = 'sls'
  const STAGE = 'dev'
  const REGION = 'eu-west-2'
  
  run(`${__dirname}/../../node_modules/serverless/bin/serverless deploy
    --verbose --stage ${STAGE} --region ${REGION} --aws-s3-accelerate`, {
      env: {
        AWS_PROFILE: `${PROJECT}-${STAGE}`
      }
  })() // <---- Add a second () here to run the function
  
  gutil.log('post-deploy')
})
```


Because gulp requires a function to be returned, when used the way I had originally intended this was how I needed it to work, but now I end up using it more often the way you are, but i haven't had time to go back and manage the repo...

**Comment by tommedema** [comment]
I see, thanks @Klathmon

**Comment by Klathmon** [comment]
No problem! I'm looking for someone to help maintain this if you are interested. Even just small things like updating the readme or cleaning up some of the error messages and things.

Let me know if you are interested!

**Comment by tommedema** [comment]
Thanks but I am actually moving away from gulp and to npm scripts. I feel
like these kind of issues are less common when just using the node API
directly (or with npm packages).

If I move back to gulp for some reason, I will let you know.
