### ISSUE TITLE
runCommand breaks colour output on Windows

### ISSUE THREAD

**Issue by soundasleep** [Klathmon/gulp-run-command#5]
I've got a Gulpfile like this:

```js
gulp.task('which-user', [], function() {
  return runCommand('bash -lc "echo $USER"', { quiet: false })();
});
```

However when it hits the runCommand, the output loses its ANSI/colours, and I get nasty colour codes:

![colours broken](https://user-images.githubusercontent.com/3889656/36009605-c0fc0bc0-0db1-11e8-9ef1-0bd16621ecdc.png)

Of course if I run `gulp --no-color`, no colour codes are output, so it works fine:

![no colours](https://user-images.githubusercontent.com/3889656/36009609-c6438c98-0db1-11e8-8a63-9fea33998e98.png)

It seems to be related to runCommand, even if I change the task to return nothing, it still breaks the colours:

```js
gulp.task('which-user', [], function() {
  return runCommand('true')();
});
```

Any ideas?

**Comment by Klathmon** [comment]
I believe this only happens on git-bash for windows, and can be solved by setting a TERM variable to something arcane and strange.

I don't have any more info for you right now, but later today if I get some time I can see if I can dig up the correct stuff.

**Comment by soundasleep** [comment]
Thank you! I know this is quite a challenging topic, I've been bashing my head against it for a while. I'm using the standard Windows Command Prompt (cmd.exe).

I tested it with git-bash. By default, it runs without colours:

![git bash no colours](https://user-images.githubusercontent.com/3889656/36079096-3aa29d48-0fe4-11e8-9ee0-58887c76b5e5.png)

When I run `gulp --color`, it works fine:

![git bash colours](https://user-images.githubusercontent.com/3889656/36079099-3f056974-0fe4-11e8-8c3c-9a6fdf15b41b.png)

So it seems to be something on the Windows Command Prompt side of things... (I'd rather not have to run git-bash, it doesn't play nicely with Cygwin)

**Comment by Klathmon** [comment]
I can't seem to get this to reproduce.

Using raw `cmd.exe` it seems to work fine on my machine. I tried your blurb above, as well as some other variations to try and get it to trigger (my gulp tasks that I'm testing with included below).

The only thing I can say is that it looks like some software somewhere is mis-interpreting the `$TERM` variable. That is the variable that will determine what kind of color codes to use, or if it should use them at all. The fact that you need to use `gulp --color` explicitly points me toward that, as well as the fact that it's gulp's output (not run through this plugin) that is dumping the color codes directly to the terminal.

I have a feeling that one of your tasks is dumping stuff into the parent environment, or something along those lines (maybe in your `which-ruby` task), and it's causing issues for the rest of the gulp commands.

Here is the set of tasks i'm trying to reproduce with. If you could give me a minimal full example that does it consistently on your machine, as well as a dump of your `$TERM` variable, I can look into it more.

```
gulp.task('default', ['thing'], runCommand('dir'))

gulp.task('thing', [], runCommand('gulp which-user'))

gulp.task('which-user', [], function() {
  return runCommand('bash -lc "echo $USER"', { quiet: false })();
});
```

**Comment by soundasleep** [comment]
`$TERM` is empty on cmd.exe, but running `bash -c "echo $TERM"` returns `cygwin`.

This is a smaller script that reproduces the issue on my machine:

```js
var gulp = require('gulp');
var runCommand = require('gulp-run-command').default;

gulp.task('default', ['build']);

gulp.task('build', ['directory'], function() { });

gulp.task('directory', [], runCommand('dir'));
```

![smaller file](https://user-images.githubusercontent.com/3889656/36080405-8fe6a262-0ff4-11e8-931f-27498b68263d.png)

Looking into it, `which dir` returns `/usr/bin/dir`.

If I change the command to:

```js
gulp.task('directory', [], runCommand('cmd /help'));
```

Then it works fine (since `which cmd` returns `/cygdrive/c/WINDOWS/system32/cmd`.  So, it looks like maybe it's Cygwin getting in the way...

**Comment by Klathmon** [comment]
Yeah I can't get it to reproduce on my machine, in either of the versions.

Sounds like it's cygwin messing with stuff, so I'd look there. See if you can set/unset the `$TERM` variable either within cygwin's config, or in the gulp-run-command options object.

I know `set TERM=ansi` has worked for me before when I had issues like this, but there are a ton of options, and from what you showed me it looks like whenever cygwin is invoked it is setting the $TERM var but not unsetting it after one of it's binaries run, so just dumping it back, or unsetting it in a batch script after each cygwin execution somehow would fix your problem (assuming i'm right, which I rarely am...)

**Comment by soundasleep** [comment]
Yep it sounds like it's something on my side. Thank you so, so much for your help - I'll keep on playing around and see if I can solve it through some scripting voodoo. I'll close this issue :)

**Comment by Klathmon** [comment]
Feel free to keep dropping info here if you think i can help, and if you figure it out let me know and I can add a note to the readme
