### ISSUE TITLE
Why is it not working with return?

### ISSUE THREAD

**Issue by MickL** [Klathmon/gulp-run-command#6]
If i pass in the function its working:

```
gulp.task('taskName', run(cmd));
```

But why it is not working if i return the function, which should be exactly the same:

```
gulp.task(taskName, () => {
    console.log(`running '${cmd}' ...`);
    return run(cmd);
});
```

**Comment by Klathmon** [comment]
Because the `run` function returns a function that gulp itself runs (in other words, `run` is curried). If you want to use it like your second example, you need to invoke the inner function like this:

```
gulp.task(taskName, () => {
            console.log(`running '${cmd}' ...`);
            return run(cmd)(); // <--- Second set of `()` will invoke the function that run returns.
        });
```

**Comment by MickL** [comment]
So `run()` returns a function, which then gets executed by `()` and returns another function which then gets executed when calling the gulp task?

Thanks for your quick response btw :)

**Comment by Klathmon** [comment]
Kind of...

Gulp takes a function, and gulp invokes it itself. If you give gulp an arrow function, then when it runs it you need to self-invoke the return value from `run`. I think an example that is fully named will help explain it best:

Your first example, fully named:
```
var run2 = run(cmd);
gulp.task('taskName', run2); // (gulp runs it via `()` internally) `run2` will return a promise, that gulp will wait on to complete.
```

You second example fully named:
```
var run3 = () => {
            console.log(`running '${cmd}' ...`);
            var run2 = run(cmd);
            var promise = run2() // <--- We are invoking it here, normally gulp does this part, but in this case gulp is doing this to `run3` below.
            return promise // run2 returns a promise that gulp will wait on to complete.
}
gulp.task(taskName, run3); // (gulp runs it via `()` internally)
```

Hope that helps!
