### ISSUE TITLE
TypeScript definitions missing

### ISSUE THREAD

**Issue by MickL** [Klathmon/gulp-run-command#8]
Hey,

could you please add TypeScript definitions?  Maybe to `@types/gulp-run-command`?

<img width="498" alt="bildschirmfoto 2018-06-19 um 14 36 48" src="https://user-images.githubusercontent.com/5103210/41597626-45fcb004-73ce-11e8-8f6f-480613ae5999.png">

Thanks!

**Comment by Klathmon** [comment]
I'm more than willing to accept a PR adding them, however I don't have the time right now to add them. Sorry
